### ISSUE TITLE
Telegram bot offline?

### ISSUE THREAD

**Issue by maurice-schleussinger** [urbanij/ScanYourPdf#1]
The Telegram bot does not respond to me anymore.

**Comment by urbanij** [comment]
Right, heroku stopped being free unfortunately, so I let it die. You can still use it locally tho: https://github.com/urbanij/ScanYourPdf/tree/master/bare

Or just run something similar to this after installing [Imagemagic](https://imagemagick.org/index.php)

`convert -density 180 <input.pdf> -rotate 0.5 -attenuate 0.2 +noise <output.pdf>`

Hope this helps
